take 无论输入的是什么形状的tensor 都当作维度是1

In [2]:
import torch

In [3]:
src = torch.tensor([[4, 3, 5],
                    [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

tile 把src当作一个数字进行重复

In [4]:
torch.tile(src, (2, 2))

tensor([[4, 3, 5, 4, 3, 5],
        [6, 7, 8, 6, 7, 8],
        [4, 3, 5, 4, 3, 5],
        [6, 7, 8, 6, 7, 8]])

In [6]:
a = torch.rand((4, 3))
a

tensor([[0.8527, 0.0411, 0.6122],
        [0.1734, 0.5020, 0.4352],
        [0.1703, 0.7811, 0.4102],
        [0.2860, 0.6319, 0.8813]])

In [13]:
a_tile = torch.tile(a, [2, 1])
a_tile

tensor([[0.8527, 0.0411, 0.6122],
        [0.1734, 0.5020, 0.4352],
        [0.1703, 0.7811, 0.4102],
        [0.2860, 0.6319, 0.8813],
        [0.8527, 0.0411, 0.6122],
        [0.1734, 0.5020, 0.4352],
        [0.1703, 0.7811, 0.4102],
        [0.2860, 0.6319, 0.8813]])

transpose函数  换轴（转置） 旋转

In [14]:
torch.transpose(a, 0, 1)

tensor([[0.8527, 0.1734, 0.1703, 0.2860],
        [0.0411, 0.5020, 0.7811, 0.6319],
        [0.6122, 0.4352, 0.4102, 0.8813]])

unbind 相当于split chunk 逐个切片返回 或者按维度逐个索引出来降了1个维度

In [15]:
torch.unbind(torch.tensor([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

unsqueeze 增维  4, --> 4, 1  或者 1, 4

In [17]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, dim=0) 
torch.unsqueeze(x, dim=1)

tensor([[1],
        [2],
        [3],
        [4]])

where 相当于三目运算

In [18]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
torch.where(x>0, x, y)

tensor([[1.0000, 0.0587],
        [0.5612, 1.7189],
        [1.0000, 1.0000]])

In [19]:
torch.where(x>0, x, 0.)

tensor([[0.0000, 0.0587],
        [0.5612, 1.7189],
        [0.0000, 0.0000]])

rand 0-1 均匀分布 randn高斯分布正太分布 rand_like(tensor) randint随机生成整数

In [ ]:
torch.rand(3, 4)
torch.randn(4, 5)
torch.randint(1, 10, (4, 5))
torch.randperm(4)  # 随机索引列表  random.shuffle(lis) 随机数据集yield -->随机梯度下降

随机种子 随机数固定可以复现

In [1]:

# manual_seed(seed) gpu上直接帮我们设置了
seed = 5
import torch.cuda
if not torch.cuda._is_in_bad_fork():
    torch.cuda.manual_seed_all(seed)

# return default_gen

随机的函数
伯努利采样

In [2]:
a = torch.empty(3, 3).uniform_(0, 1)
a

tensor([[0.9410, 0.7955, 0.9180],
        [0.8860, 0.4812, 0.9060],
        [0.4795, 0.2600, 0.7186]])

基于上边的概率返回0， 1

In [4]:
torch.bernoulli(a)

tensor([[1., 1., 1.],
        [1., 0., 1.],
        [0., 0., 1.]])

normal函数 正态分布

In [6]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1.0, 0, -0.1))

tensor([2.3713, 0.5450, 1.7735, 5.3937, 5.2730, 5.3864, 7.1884, 8.0545, 9.2434,
        9.9747])

In [8]:
torch.normal(mean=0, std=1, size=(1, 4))

tensor([[0.4017, 0.5795, 0.8680, 0.3339]])